config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cards#index"

  resources :cards, only: [:index, :show]

  resources :trades do
    resources :requests, only: [:new, :create], shallow: true
  end

  resources :requests, only: [:destroy]

  resources :collections, shallow: true do
    post 'add_to_collection', on: :collection
    delete 'remove_from_collection', on: :member
    resources :cards, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :wantlists, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  post 'wantlists/add_to_wantlist', to: 'wantlists#add_to_wantlist', as: 'add_to_wantlist_wantlists'

  resources :trade_items, only: [:index, :show]

  resources :users, only: [] do
    resources :collections, only: [:index, :show], controller: 'users/collections'
    resources :trades, only: [:index, :show], controller: 'users/trades'
  end

  get '/search', to: 'application#search'

  patch "/requests/:id/accept", to: "requests#accept", as: "accept"
  patch "/requests/:id/reject", to: "requests#reject", as: "reject"
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :cards
  validates :user, presence: true 
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  def index
    @collections = policy_scope(Collection)
  end

  def show
  end

  def new
    @collection = Collection.new
    @cards = Card.all
    begin
      authorize @collection
    rescue Pundit::NotAuthorizedError => e
      Rails.logger.debug("Authorization failed for user: #{current_user.inspect}")
      Rails.logger.error("Authorization error: #{e.message}")
    end
  end

  def create
    @collection = Collection.new
    @collection.user = current_user
    authorize @collection

    if @collection.save
      if params[:collection][:card_ids].present?
        selected_cards = Card.find(params[:collection][:card_ids])
        @collection.cards << selected_cards
      end
      redirect_to @collection, notice: 'Collection was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @collection.update(collection_params)
      redirect_to @collection, notice: 'Collection was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @collection
    @collection.destroy
    redirect_to collections_url, notice: 'Collection was successfully destroyed.'
  end

  def add_to_collection
    # @collection = current_user.build_collection(collection_params) unless current_user.collection
    # @collection = current_user.create_collection(collection_params) unless current_user.collection
    # @collection ||= current_user.collection
    @collection = current_user.collection || current_user.create_collection
    card = Card.find(params[:card_id])
    authorize @collection

    unless @collection.cards.include?(card)
      @collection.cards << card
      flash[:notice] = "Card added to your collection!"
    else
      flash[:alert] = "You already have this card in your collection."
    end

    redirect_to cards_path
  end

  def remove_from_collection
    @collection = Collection.find(params[:id])
    card = Card.find(params[:card_id])
    authorize @collection

    # Assuming you have a many-to-many association between collections and cards
    @collection.cards.delete(card)

    redirect_to collections_path, notice: 'Card removed from collection!'
  end

  private

  def set_collection
    @collection = Collection.find(params[:id])
    authorize @collection
  end

  def collection_params
    params.require(:collection).permit(:user_id)
  end

end

app/views/collections/edit.html.erb
<h1>here we should render a form</h1>

app/views/collections/index.html.erb
<h2>My Collection</h2>

<% @collections.each do |collection| %>
  <% collection.cards.each do |card| %>
  <div>
  <img src="<%= card.image_url %>" alt="<%= card.name %>">
    <%= button_to 'REMOVE FROM COLLECTION', remove_from_collection_collection_path(collection, card_id: card.id), method: :delete, class: 'btn btn-danger' %>
  </div>
  <% end %>
<% end %>

app/views/collections/new.html.erb
<h1>here we should render a form</h1>
<%= form_with(model: @collection, local: true) do |form| %>

  <% if @cards.any? %>
    <div class="form-group">
      <div class="form-group">
        <%= form.submit "Create Collection", class: 'btn btn-primary' %>
      </div>
      <%= form.label :card_ids, "Select Cards" %>
      <ul>
        <% @cards.each do |card| %>
          <li>
            <%= check_box_tag 'collection[card_ids][]', card.id, @collection.card_ids.include?(card.id), id: dom_id(card) %>

            <%= label_tag dom_id(card) do %>
              <%= image_tag card.image_url, size: "200x300" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <p>No cards available.</p>
  <% end %>

<% end %>

app/views/collections/show.html.erb
<h1>collections show page</h1>