config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cards#index"

  resources :cards, only: [:index, :show]

  resources :trades do
    resources :requests, only: [:new, :create], shallow: true
  end

  resources :requests, only: [:destroy]

  resources :collections, shallow: true do
    post 'add_to_collection', on: :collection
    delete 'remove_from_collection', on: :member
    resources :cards, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :wantlists, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  post 'wantlists/add_to_wantlist', to: 'wantlists#add_to_wantlist', as: 'add_to_wantlist_wantlists'

  resources :trade_items, only: [:index, :show]

  resources :users, only: [] do
    resources :collections, only: [:index, :show], controller: 'users/collections'
    resources :trades, only: [:index, :show], controller: 'users/trades'
  end

  get '/search', to: 'application#search'

  patch "/requests/:id/accept", to: "requests#accept", as: "accept"
  patch "/requests/:id/reject", to: "requests#reject", as: "reject"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "cardswapp-transparent2.png" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item-a">
              <%= link_to "My Collection", collections_path, class: "nav-link" %>
            </li>
            <li class="nav-item-a">
              <%= link_to "My Wantlist", wantlists_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu", style: "object-fit: cover" %>
            </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My Trades", trades_path, class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>