config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cards#index"

  resources :cards, only: [:index, :show]

  resources :trades do
    resources :requests, only: [:new, :create], shallow: true
  end

  resources :requests, only: [:destroy]

  resources :collections, shallow: true do
    post 'add_to_collection', on: :collection
    delete 'remove_from_collection', on: :member
    resources :cards, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :wantlists, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  post 'wantlists/add_to_wantlist', to: 'wantlists#add_to_wantlist', as: 'add_to_wantlist_wantlists'

  resources :trade_items, only: [:index, :show]

  resources :users, only: [] do
    resources :collections, only: [:index, :show], controller: 'users/collections'
    resources :trades, only: [:index, :show], controller: 'users/trades'
  end

  get '/search', to: 'application#search'

  patch "/requests/:id/accept", to: "requests#accept", as: "accept"
  patch "/requests/:id/reject", to: "requests#reject", as: "reject"
end

app/models/card.rb
class Card < ApplicationRecord
  validates :name, :set, :rarity, :type, presence: true
  self.inheritance_column = :_type_disabled
  has_and_belongs_to_many :collections
  has_many :wantlist_items
  has_many :wantlists, through: :wantlist_items
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    if params[:query].present?
      @cards = policy_scope(Card).where("name ILIKE ?", "%#{params[:query]}%")
    else
      # @cards = policy_scope(Card)
      @cards = policy_scope(Card).order(created_at: :desc).limit(12)
    end
  end

  def show
    @card = Card.find(params[:id])
    authorize @card
  end

end

app/views/cards/index.html.erb
<h1>New Cards on CardSwapp</h1>

<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: cards_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search by card name"
      %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<% if @cards.any? %>
  <div class="row">
    <% @cards.each do |card| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <img src="<%= card.image_url %>" alt="<%= card.name %>" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title"><%= card.name %></h5>
            <%= button_to 'HAVE', add_to_collection_collections_path(card_id: card.id), method: :post, class: 'btn btn-primary' %>
            <%= button_to 'WANT', add_to_wantlist_wantlists_path(card_id: card.id), method: :post, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No cards found for '<%= params[:query] %>'</p>
<% end %>

app/views/cards/show.html.erb
<h1>cards show</h1>